export const randomTweets = [
    "Finalmente consegui aquela promoção! Muito feliz com essa nova etapa. Agora é foco total 💪✨",
    "Dia difícil... Perdi meu celular no metrô e tô arrasado 😔. Quem nunca passou por isso, né?",
    "Gente, alguém mais tá viciado em café ou sou só eu? Já tô no meu quarto do dia 😂☕",
    "Comecei a ler um livro incrível ontem à noite! Não vejo a hora de continuar hoje 📖😍",
    "Acabei de fazer a melhor pizza da minha vida, e foi com uma receita que achei no TikTok 🍕🙌",
    "Acordei cedo pra ir à academia e tá sendo a melhor decisão da minha semana! #Foco #Disciplina",
    "Trabalhei o dia inteiro, mas ainda não consigo parar de pensar nas férias que estão chegando ✈️🏖️",
    "Hoje o dia foi pesado... Mas sobrevivi. Amanhã é um novo dia, né? 🌧️➡️🌞",
    "Perdi o ônibus por 30 segundos. Já aconteceu com vocês? Que raiva! 😡",
    "Ganhei uma baita oportunidade de trabalho hoje! Parece que as coisas estão finalmente entrando nos eixos 🙏",
    "Passei o dia com a minha família e foi incrível. Nada como estar perto de quem a gente ama ❤️",
    "Tô triste... Não consegui a bolsa de estudos que eu queria. Mas não vou desistir! 💪",
    "Hoje foi dia de maratona de séries! Consegui terminar 3 temporadas, alguém me segura! 🍿😂",
    "Caminhei no parque ao pôr do sol e foi lindo demais. Natureza realmente tem um poder de cura 🌅🌿",
    "Fui no shopping só pra 'dar uma olhada'... Voltei cheio de sacolas. Ops! 😅💸",
    "Amanhã é o grande dia, minha primeira corrida de 5km! Espero não desmaiar no meio do caminho 😂🏃‍♂️",
    "Fiquei preso no trânsito por quase 2 horas hoje. Cidade grande tem dessas... 😩🚗",
    "Recebi uma mensagem inesperada de um amigo antigo hoje. Que nostalgia boa 🥺✨",
    "Passei o dia estudando e acho que minha cabeça vai explodir! Mas faz parte, foco no objetivo 💻📚",
    "Não sei vocês, mas tô precisando de férias urgentemente... A cabeça não tá aguentando mais 😓🌴",
    "Hoje foi um dia incrível! Passei a tarde na praia e terminei com um pôr do sol maravilhoso 🌅😍",
    "Tive que cancelar meus planos de viagem... Às vezes as coisas não saem como a gente quer 😔",
    "Minha filha falou suas primeiras palavras hoje! Que emoção indescritível 😭👶",
    "Recebi um feedback super positivo no trabalho! Faz tudo valer a pena 😊🙌",
    "Tentei uma receita nova hoje e, olha... Ficou uma catástrofe 😂👩‍🍳 #CulinaristaDePrimeiraViagem",
    "Tive um sonho estranho essa noite e acordei super confuso. Alguém mais sonha com coisas sem sentido?",
    "Cortei meu cabelo bem curtinho e tô me sentindo outra pessoa. Mudanças são boas ✂️✨",
    "Perdi um contrato importante hoje... mas vou continuar tentando. A vida segue!",
    "Aquele momento em que você percebe que deixou o guarda-chuva em casa e começa a chover ☔🙃",
    "Vi um filme maravilhoso hoje, me fez pensar em tantas coisas da vida... Recomendo demais 🎬🍿",
    "Ganhei um presente surpresa hoje! Me sinto tão querido. Essas pequenas coisas fazem o dia melhor 💝",
    "Parece que tô vivendo o mesmo dia várias vezes. Alguém mais se sente assim às vezes?",
    "Passei o dia inteiro organizando a casa, mas agora tá tudo em ordem. Sensação de dever cumprido 🏡😊",
    "Hoje é meu aniversário e só posso agradecer por mais um ano de vida 🎉🙏",
    "Fiz uma doação para uma causa que acredito hoje. Se cada um fizer sua parte, a mudança vem 💚",
    "Joguei videogame com amigos a tarde toda, foi divertido demais! Às vezes é bom desligar um pouco 🎮",
    "Recebi uma notícia inesperada hoje... ainda tô processando. A vida sempre nos surpreende",
    "Voltei a estudar algo novo e, sinceramente, tá sendo bem mais desafiador do que eu esperava! 📚",
    "Tô numa vibe de playlists antigas... Redescobrindo músicas que eu amava há anos 🎧💿",
    "Hoje minha avó me contou histórias da infância dela. Que momentos especiais, são memórias pra vida toda ❤️",
]